### ISSUE TITLE
Move data into separate files

### ISSUE THREAD

**Issue by sohan2410** [kunaljain0212/git-init-FOSS-API#3]
Instead of using objects for projects & students we can store them in a csv file and import them wherever required as json object using [csvtojson](https://www.npmjs.com/package/csvtojson)

**Comment by kunaljain0212** [comment]
Great idea @sohan2410, go ahead!
This change will also make the code a bit cleaner than its current version.

**Comment by kunaljain0212** [comment]
Tagging @hs2361 for visibility

**Comment by sohan2410** [comment]
Yeah sure, so I'll be keeping separate JSON files for projects, students & score and keep them in public folder.
