### ISSUE TITLE
[DOCUMENTATION] Create Readme

### ISSUE THREAD

**Issue by kunaljain0212** [kunaljain0212/git-init-FOSS-API#4]
Create a Readme similar to the frontend repo of this website (``https://github.com/aaryak-shah/git-init-FOSS``).

Things to note:
1. Local setup steps may differ
2. Features are to be added accordingly
3. This server has a cron job built-in which run every 1 hour and updates the scores of participants in ``score.json`` file, which is then served using a single endpoint to the frontend. Try including about the cron job in the README. Also you can read more about crontab and how it can be used to run the cron job locally using ``script.cron`` file.

**Comment by arushi2715** [comment]
Hey @kunaljain0212  I would like to work on this.
Would you please assign this to me?

**Comment by kunaljain0212** [comment]
Tagging @hs2361 for visibility
